from pyttsx3 import speak
from time import sleep
while True:
    speak("hat")
    sleep(5)
    speak("coat")
    sleep(5)
    speak("jacket")
    sleep(5)
    speak("scarf")
    sleep(5)
    speak("gloves")
    sleep(5)
    speak("shoes")
    sleep(5)
    speak("trainers")
    sleep(5)
    speak("boots")
    sleep(5)
    speak("suit")
    sleep(5)
    speak("socks")
    sleep(5)
    speak("t-shirt")
    sleep(5)
    # speak("watch")
    # sleep(5)
    speak("shirt")
    sleep(5)
    speak("dress")
    sleep(5)
    speak("ring")
    sleep(5)
    speak("belt")
    sleep(5)
    speak("sweater")
    sleep(5)
    speak("jumper")
    sleep(5)